{include file='admin/before_body.phtml' title='内容管理列表'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='system_view'}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="{url('admin/system')}">系统设置</a></li>
          <li class="current">邮件模板列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}

      <!-- start -->
         <table class="table table-striped table-bordered table-checkable table-highlight-head table-no-inner-border table-hover"> 
          <thead> 
           <tr>
            <th>邮件模板名称</th> 
            <th width="50"> 操作 </th> 
           </tr> 
          </thead> 
          <tbody>
           <tr>
            <td>用户注册邮件模板</td> 
            <td class="align-center"> 
              <a href="{url('admin/system/emailmod/register')}" class="bs-tooltip" data-original-title="修改"><i class="icon-pencil"></i></a>
            </td>
           </tr>
           <tr>
            <td>忘记密码邮件模板</td> 
            <td class="align-center"> 
              <a href="{url('admin/system/emailmod/password')}" class="bs-tooltip" data-original-title="修改"><i class="icon-pencil"></i></a>
            </td>
           </tr>
          </tbody> 
         </table>
      <!-- /end -->
    </div>
  </div>
</div>
</body>
{include file='admin/after_body.phtml'}
</html>
