<!DOCTYPE html>
<html lang="zh-CN">  
<head>
<meta charset="utf-8">
<title>{$title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<link href="{$tpldir}/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="{$tpldir}/css/fontawesome/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="{$tpldir}/css/style.css" rel="stylesheet" type="text/css" />
{html_css}
<link href="{$tpldir}/css/responsive.css" rel="stylesheet" type="text/css" />
<link href="{$tpldir}/css/plugins.css" rel="stylesheet" type="text/css" />
</head>