<header class="header navbar navbar-fixed-top" role="banner">
  <div class="container">
    <ul class="nav navbar-nav">
      <li class="nav-toggle">
        <a href="javascript:void(0);">
          <i class="icon-reorder">
          </i>
        </a>
      </li>
    </ul>
    <a class="navbar-brand" href="{url('admin')}">
      <strong>TTGG 管理后台</strong>
    </a>
    <a href="#" class="toggle-sidebar bs-tooltip" data-placement="bottom"
    data-original-title="左侧导航折叠">
      <i class="icon-reorder"></i>
    </a>
    <ul class="nav navbar-nav navbar-left hidden-xs">
      <li><a href="{url('admin')}">首页</a></li>
      {if access('product-view')}
      <li><a href="{url('admin/product')}">商品管理</a></li>
      {/if}
      {if access('merchant-view')}
      <li><a href="{url('admin/merchant')}">商家中心</a></li>
      {/if}
      {if access('user-view')}
      <li><a href="{url('admin/user')}">用户管理</a></li>
      {/if}
      {if access('ad-view')}
      <li><a href="{url('admin/ad')}">广告管理</a></li>
      {/if}
      <li><a href="javascript:;">数据统计</a></li>
      {if access('score-edit')}
      <li><a href="{url('admin/system')}">系统设置</a></li>
      {/if}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{url('')}" target="_blank">前台首页</a></li>
      <li class="dropdown user">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="icon-male">
          </i>
          <span class="username">
            {$account->nickname}
          </span>
          <i class="icon-caret-down small">
          </i>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="{url('admin/user/clearAllCache')}">
              <i class="icon-key"></i>清空所有缓存
            </a>
          </li>
          <li>
            <a href="{url('user/logout')}">
              <i class="icon-key"></i>退出
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</header>
