{include file='before_body.phtml' title='天天逛逛登陆注册页'}
  <body>
    {if isset($login)}

    <div id="wrapper">
      <div class="scroller">
        <header>
          <h1>登录</h1>
          <a class="back" href="javascript:window.history.back();"></a>
          <a class="head-fr" href="{url('user/register')}">注册</a>
        </header>
        <div class="login">
          <div class="title">
            <h2>天天逛逛账号登录</h2>
          </div>
          <form autocomplete="off"  id="login" method="POST">
            <div class="opt-box">
              <div class="opt-group">
                <label for="loginName" class="lg-name">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="text" id="loginName" name="username" placeholder="输入手机/昵称">
                </div>
              </div>
              <div class="opt-group">
                <label for="loginPwd" class="lg-pwd">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="password" id="loginPwd" name="password" placeholder="输入密码">
                </div>
              </div>
            </div>
            <input type="submit" class="btn" value="登录">
          </form>
          <p class="p-right">
            <a target="_blank" href="">忘记密码？</a>
          </p>
          <div class="title t-blow">
            <h2>第三方账号快速登录</h2>
          </div>
          <div class="btn-below">
            <a target="_blank" href="{url('user/qqLogin')}">
              <i></i>
              <span>QQ登录</span>
            </a>
          </div>
        </div>
        <footer>
          <a id="backTop" href="javascript:void(0);">
            <i></i>
          </a>
        </footer>
      </div>
    </div>
  {else}
    <div id="wrapper">
      <div class="scroller">
        <header>
          <h1>注册</h1>
          <a class="back" href="javascript:window.history.back();"></a>
          <a class="head-fr" href="{url('user/login')}">登录</a>
        </header>
        <div class="login">
          <div class="title">
            <h2>天天逛逛账号注册</h2>
          </div>
          <form id="regist" method="POST" autocomplete="off"  style="display:block">
            <div class="opt-box">
              <div class="opt-group">
                <label for="registName" class="lg-name">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="text" name="username"  value="" placeholder="输入手机/用户名">
                </div>
              </div>
              <div class="opt-group">
                <label for="registPwd" class="lg-pwd">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="password" id="registPwd" value="" name="password" placeholder="密码">
                </div>
              </div>
              <div class="opt-group">
                <label for="registPwdCheck" class="lg-pwd">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="password" id="registPwdCheck" value="" name="repassword" placeholder="请再次输入密码">
                </div>
              </div>
              <div class="opt-group">
                <label for="registEmail" class="lg-email">
                  <i></i>
                </label>
                <div class="opt">
                  <input type="text" id="registEmail" value="" name="email" placeholder="输入邮箱">
                </div>
              </div>
            </div>
            <div class="code">
              <div class="opt-box">
                <div class="opt">
                  <input type="text" name="captcha" placeholder="验证码">
                </div>
              </div>
              <div class="code-pic">
                <div class="pic-box">
<a href="#" class="fr"><img src="{url('user/captcha')}" onclick="this.src='{url('user/captcha')}?_=' + Math.random()" width="150" height="38">
               </a> </div>
              </div>
            </div>
            <div class="confirm">
              <label class="checkbox">
                <i></i>
                <input type="checkbox" id="checkbox1">我已阅读并同意使用天天逛逛的<a target="_blank" href="">《服务条款》</a>
              </label>
            </div>
            <input type="submit" class="btn" value="注册">
          </form>
        </div>
        <footer>
          <a id="backTop" href="javascript:void(0);">
            <i></i>
          </a>
        </footer>
      </div>
    </div>
     {/if}
{include file='after_body.phtml'}
<script type="text/javascript">
$(document).ready(function() {
  /**勾选框样式**/
  $('#checkbox1').click(function() {
    $(this).siblings('i').toggleClass('active');
  });
});
</script>
  </body>
</html>








<script type="text/javascript">
{if isset($loginMsg)}
    appendMsg($('#login').find("input[name='username']"), '{$loginMsg}', 'error');
{/if}
{if isset($captchError)}
    appendMsg($('#regist').find("input[name='captcha']"), '{$captchError}', 'error');
{/if}
{if isset($userError)}
    appendMsg($('#regist').find("input[name='username']"), '{$userError}', 'error');
{/if}
{if isset($msg)}
  dialog('{$msg}').open();
{/if}
{literal}
function isEmpy(str) {
  if ( str == '' || str == null) return true;
  var regu = '^[ ]+$';
  var re = new RegExp(regu);
  return re.test(str);
}
function isEmail(str){
  var regu = '^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$';
  var re = new RegExp(regu);
  return re.test(str);
}
function appendMsg(object, msg, type){
  if (msg !== '') {
    object.parent().parent().append('<div class="org from-msg">' + msg + '</div>');
  }
  if (type === 'error') {
    object.after('<em class="cha from-msg"></em>');
  } else if (type === 'success') {
    object.after('<em class="dui from-msg"></em>');
  }
}

$(function () {
  $('#login').submit(function() {
    var from = $(this), error = false,
    username = from.find("input[name='username']"),
    password = from.find("input[name='password']");
    $('.from-msg').remove();
    if (isEmpy(username.val())) {
      appendMsg(username, '用户名不能为空', 'error');
      error = true;
    }
    if (isEmpy(password.val())) {
      appendMsg(password, '密码不能为空', 'error');
      error = true;
    }
    if (error){
      return false;
    }
  });

  $('#regist').submit(function() {
    var from = $(this), error = false,
    username = from.find("input[name='username']"),
    email = from.find("input[name='email']"),
    captcha = from.find("input[name='captcha']"),
    repassword = from.find("input[name='repassword']"),
    password = from.find("input[name='password']");
    $('.from-msg').remove();
    if (isEmpy(username.val())) {
      appendMsg(username, '用户名不能为空', 'error');
      error = true;
    } else if(!username.val().match(/\w{0,16}/)) {
        appendMsg(username, '用户名只能由字母或下划线或数字组合哦,最长只能16位', 'error');
        error = true;
    } else {
        appendMsg(username, '', 'success');
    }

    if (isEmpy(password.val())) {
      appendMsg(password, '密码不能为空', 'error');
      error = true;
    } else if (!password.val().match(/\w{6,20}/)) {
      appendMsg(password, '只能由6~20位的字母或下划线或数字组合', 'error');
      error = true;
    }  else {
      appendMsg(password, '', 'success');
      if (password.val() === repassword.val()) {
        appendMsg(repassword, '', 'success');
      } else {
        appendMsg(repassword, '两次密码不一样', 'error');
        error = true;
      }
    }

    if (!isEmpy(email.val()) && !isEmail(email.val())){
      appendMsg(email, '邮箱地址格式不正确', 'error');
      error = true;
    }

    if (isEmpy(captcha.val())) {
      appendMsg(captcha, '验证码不能为空', 'error');
      error = true;
    }
    if (error){
      return false;
    }
  });
});
{/literal}
</script>
</body>
</html>
