{include file='merchant/before_body.phtml' title='账户充值'}
<body>
{include file='merchant/header.phtml' match="我的账户"}
  <div class="container">
    {include file='merchant/user_sidebar.phtml' match="资金管理"}

    <div class="main">
      {if isset($step) && $step == 1}
      <h2>充值成功</h2>
      <p class="warning">订单成功</p>
      <p class="warning">充值金额 {$smarty.get.total_fee|default:0|escape}，完成时间 {$smarty.get.notify_time|default:0|escape}</p>
      <p class="warning">订单号：{$smarty.get.trade_no|default:0|escape}</p>
      {else}
      <h2>资金账户充值</h2>
      <p class="warning">为了保证您的账户资金安全，请您先进行身份认证后再进行充值。</p>
      <div class="input-area">
        <form action="" method="POST">
          <div>
            <label>充值金额：</label>
            <input type="text" name="WIDtotal_fee" value="">
            {if isset($msg) && $msg}
            <div class="error"><i></i>{$msg}</div>
            {/if}
          </div>
          <input type="submit" value="提交" class="btn3">
        </form>
      </div>
      {/if}
    </div>
  </div>
</body>
{include file='merchant/after_body.phtml'}
</html>
