{include file='merchant/before_body.phtml'}
<body>
{include file='merchant/header.phtml' match="我的账户"}

  <div class="container">
    {include file='merchant/user_sidebar.phtml' match="修改密码"}

    <div class="main">
      <h2>修改支付密码</h2>
      <div class="input-area">
        <form action="" method="POST">
        {if isset($step) && $step == 1}
          <div>
            <label>原始的密码：</label>
            <input type="password" name="password">
          </div>
        {/if}
          <div>
            <label>设置新密码：</label>
            <input type="password" name="pay_password">
          </div>
          <div>
            <label>确认新密码：</label>
            <input type="password" name="pay_password_confirmation">
            {if isset($msg) && $msg}
            <div class="error"><i></i>{$msg}</div>
            {/if}
          </div>
          <input type="submit" value="提交" class="btn2">
        </form>
      </div>
    </div>
  </div>
</body>
{include file='merchant/after_body.phtml'}
</html>
