{include file='before_body.phtml' title=''}
<body>
{include file='header.phtml'}


<div class="main">
<div class="static">
  <div class="static_fl">
    <ul id="help">
      <li class="cur">
      	<a href="javascript:;"><i class="icon-caret-right"></i>新手帮助</a>
      	<i class="icon-caret-down"></i>
      	<span ltab="1">新手上路</span>
      	<span ltab="2">抢购攻略</span>
      </li>
      <li>
      	<a href="javascript:;"><i class="icon-caret-right"></i>商品相关</a>
      	<i class="icon-caret-down"></i>
      	<span ltab="3">商品常见问题</span>
      </li>
      <li>
      	<a href="javascript:;"><i class="icon-caret-right"></i>积分相关</a>
      	<i class="icon-caret-down"></i>
      	<span ltab="4">什么是积分</span>
      	<span ltab="5">如何挣积分</span>
      </li>
    </ul>
  </div>

  <div class="static_fr">

  	<div class="tab on" id="con1">

	    <div class="title_top">新手上路</div>
	    <dl id="helpcontent">
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>挑选宝贝，了解宝贝详情</a>
	        <div class="content">点击按钮提前进入天天逛逛，其次进入内页查看宝贝详情及评价。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>点击去抢购，到淘宝网购买</a>
	        <div class="content">提前在天天逛逛&淘宝网保持登录状态，抢到好东西付款要快。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>卖光后也依然能以原价购买</a>
	        <div class="content">如果真心喜欢又卖光了，也可以点击按钮到淘宝网以原价购买。</div>
	      </dt>
	    </dl>

  	</div>

  	<div class="tab" id="con2">

	    <div class="title_top">抢购攻略</div>
	    <dl id="helpcontent">
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>每天上新</a>
	        <div class="content">每天早上9点以后天天逛逛都会上新产品，挑选心仪的宝贝，在未抢购完之前，坐等开抢时刻的到来。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>提前登录天天逛逛和淘宝</a>
	        <div class="content">很多人在抢购时因为自己粗心未登录账号而导致与宝贝失之交臂，在此特别提醒大家在抢购还未开始时必做的准备是：登录天天逛逛和淘宝帐号。</div>
	      </dt>
	    </dl>

  	</div>

  	<div class="tab" id="con3">

	    <div class="title_top">商品常见问题</div>
	    <dl id="helpcontent">
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>我要购买在天天逛逛上看到的东西,怎样操作？</a>
	        <div class="content">天天逛逛网不出售任何宝贝，只是一个导购网、购物分享交流平台。您看到的所有宝贝信息均来自合作商城，您需要到相应的店铺或商城完成网购交易，关于具体的宝贝信息，也需要您去相关购物商城进行咨询。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>为什么在天天逛逛看到的宝贝价格和在淘宝看到的价格不一致？</a>
	        <div class="content">部分卖家会使用淘宝提供的优惠方式进行活动，如果您看到价格不一致，那可能就是该宝贝使用了如下折扣方式：拍下改价、VIP价格、优惠券价格。是否是拍下改价、VIP价格、优惠券价格宝贝，天天逛逛会在宝贝标题描述中提示。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>什么是拍下改价？</a>
	        <div class="content">拍下改价是淘宝卖家设定的一种促销方式，宝贝不显示活动价，直接拍下宝贝后会自动变成活动价。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>什么是VIP价格？</a>
	        <div class="content">很多卖家使用的是淘宝提供的VIP打折形式，只有淘宝VIP会员登录后才可以看到优惠价格。如果您是淘宝VIP会员，请直接登陆购买。如果是非VIP会员，请询问卖家是否可按优惠价格购买。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>什么是优惠券价格？</a>
	        <div class="content">卖家会设置使用优惠券才能享折后的价格，只有领取优惠券才能以天天逛网的价格购买到宝贝。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>为什么宝贝不包邮？</a>
	        <div class="content">偏远地区不包邮：由于部分卖家会设置西藏、新疆、内蒙古、青海、宁夏、甘肃等地区需要补充邮费。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>为什么活动刚开始，打开宝贝页面后却显示已下架？</a>
	        <div class="content">款宝贝数量有限：部分宝贝由于是限量销售，所以拼抢很激烈，甚至在几秒的时间内就可能被抢光，库存被拍光后，该宝贝就会显示已下架。这完全属于正常现象，但我们保证活动一定是真实的，每一款宝贝都是天天逛逛网的小编跟卖家软磨硬泡谈来的，并且所有成交都是在淘宝平台上成交，任何人都做不了假。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>怎样判断活动的真实性？</a>
	        <div class="content">查看成交记录：淘宝宝贝成交后都会有成交记录，宝贝详情页内可以查询，包括成交时间 、买家名称、成交价格、成交数量等信息。只要看活动开始时段的成交记录就可以知道活动是否虚假啦！</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>卖家不发货或虚假发货怎么办？</a>
	        <div class="content">如遇到不发货或一些卖家违返协议的问题，可以通过淘宝的正常渠道投诉卖家。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>从天天逛逛网去购物可以货到付款吗?</a>
	        <div class="content">针对淘宝来说，只要店家支持货到付款，则从天天逛逛网到淘宝购物可以货到付款。但该笔交易需等到卖家通过快递收到货款，才算真正完成。</div>
	      </dt>
	    </dl>

  	</div>

  	<div class="tab" id="con4">

	    <div class="title_top">什么是积分</div>
	    <dl id="helpcontent">
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>什么是积分</a>
	        <div class="content">积分是天天逛逛网提供的积分服务，用户通过在天天逛逛网、九块九包邮以及20元封顶进行签到、完成任务等操作时获得的通用虚拟货币，拥有积分后，用户可以在积分商城参与兑换集分宝，用户使用积分时需遵守网站公布的最低使用数量等要求。积分不可转让或换取现金。</div>
	      </dt>
	    </dl>

  	</div>

  	<div class="tab" id="con5">

	    <div class="title_top">如何挣积分</div>
	    <dl id="helpcontent">
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>网站签到</a>
	        <div class="content">点击签到，获得<strong>5-40</strong>积分每日在天天逛逛签到可得积分。第一天签到领取<strong>5</strong>积分，连续签到每天增加5积分，连续七天以上签到可获得<strong>40</strong>积分。如果中断领取，又会从5积分开始。</div>
	      </dt>
	      <dt><a href="javascript:;"><i class="icon-caret-right"></i>新用户注册</a>
	        <div class="content">新用户注册或联合登录用户完善注册信息可获得<strong>100</strong>积分。</div>
	      </dt>
	    </dl>

  	</div>

  </div>
</div>
</div>
{literal}
<style type="text/css">
.hidden{display: none;}
.static{clear: both; overflow: hidden; padding: 20px;}
.static .static_fl{float: left; width: 175px; overflow: hidden;}
.static .static_fl ul li{margin: 10px 0 0; border-right: 0; text-align: center; position: relative;}
.static .static_fl ul li a{display: block; height: 36px; line-height: 36px; border: 1px solid #cdcdcd; background: url(/static/default/images/help_bg1.png) repeat-x; font-size: 14px; font-weight: bold; margin-bottom: 10px;}
.static .static_fl ul li a .icon-caret-right{margin-right: 5px; font-size: 16px;}
.static .static_fl ul li a:hover{text-decoration: none; color: #fff; background: url(/static/default/images/help_bg2.png) repeat-x;}
.static .static_fl ul li .icon-caret-down{display: none; font-size: 16px;}
.static .static_fl ul .cur .icon-caret-down{position: absolute; top: 31px; left: 84px; display: block; color: #ff9410;}
.static .static_fl ul li span{display: none; font-weight: bold; height: 30px; line-height: 30px; font-size: 14px; color: #707070; cursor: pointer;}
.static .static_fl ul .cur a{border-right: 0; color: #fff; background: url(/static/default/images/help_bg2.png) repeat-x;}
.static .static_fl ul .cur span{display: block;}

.static .static_fr{min-height:400px; border-left: 1px solid #cdcdcd; width: 734px; margin: 10px 0 0; padding: 0 0 0 30px; float: right;}
.static .static_fr .title_top{border-bottom: 1px solid #ddd; height: 36px; line-height: 36px; font-size: 14px; font-weight: bold; color: #666; padding: 0 5px; clear: both; overflow: hidden;}
.static .static_fr dl{padding: 10px; clear: both; overflow: hidden;}
.static .static_fr dl dt{float: left; width: 357px; line-height: 30px; overflow: hidden;}
.static .static_fr dl dt i{color: #ff8800; font-size: 16px; margin: 0 5px 0 0;}
.static .static_fr dl dt a:hover{text-decoration: none;}
.static .static_fr dl dt .content{width: 330px; overflow: hidden; padding: 0 0 0 15px; display: none; color: #999;}
.static .static_fr dl dt .content strong{color: #ff8800;}
.static .static_fr dl .on .content{display: block;}
.tab{display: none;}
.on{display: block;}
</style>
{/literal}
{include file='footer.phtml'}
</body>
{include file='after_body.phtml'}
<script type="text/javascript">
$('#help > li').click(function(){
  $(this).addClass("cur").siblings().removeClass();
});
$('#help > li > span').click(function(){
  var tab = $(this).attr('ltab');
  $('.tab').siblings().removeClass("on");
  $('#con' + tab).addClass("on");
});
$('#helpcontent > dt').click(function(){
  $(this).addClass("on").siblings().removeClass();
  $(this).find('i').removeClass().addClass("icon-caret-down");
  $(this).siblings().find('i').addClass("icon-caret-right");
});
</script>
</html>
