{include file='before_body.phtml' title='双11提前抢！击穿底价，舍我其谁，物价回到十年前，全场1折起！' description='双11,天天逛逛双11豪礼抢先抽!爱疯6,奢侈品应有尽有!提前抢购,赢免单和万元奖!100%正品保证!24h闪电发货!贴心服务!全场包邮!'}
<body style="background-color:#ff7ea0;">
{literal}
<style type="text/css">
body{min-width: 1340px;}
.clear{clear:both;}
.db-header{width:100%; min-width:1340px; height:682px; background:url(/static/default/images/topic/banner.png) repeat center center;}
.db-main{width:980px; margin:0 auto; position:relative;}
.db-main .top-ad{display:block; width:980px; height:160px; margin-top:-150px; margin-bottom:20px;}
.db-nav{width:160px; z-index:3000;}
.abs-nav{position:absolute; top:158px; *top:10px; right:-180px;}
.fixed-nav{position:fixed; top:0;}
.db-nav .title-icon,.db-nav .odd a,.db-nav .even a,.db-nav .back-top,.db-nav .parent-list .odd a:hover,.db-nav .parent-list .even a:hover,.db-nav .child-list li a:hover{background:url(/static/default/images/topic/nav_icon_11.png) no-repeat;}
.db-nav .title-icon{background-position:0 0; width:160px; height:53px;}
.db-nav ul{list-style-type:none; text-align:center; margin:0; padding:0;}
.db-nav ul li a{color:#fff; text-decoration:none; display:block;}
.db-nav ul li a:hover{color:#000;}
.db-nav .parent-list{line-height:41px; font-size:20px;}
.db-nav .child-list{line-height:27px; font-size:13px;}
.db-nav .parent-list li a{width:160px; height:41px;}
.db-nav .child-list li a{width:160px; height:27px;}
.db-nav .parent-list .odd a{background-position:0 -100px;}
.db-nav .parent-list .odd a:hover{background-position:0 -298px;}
.db-nav .parent-list .even a{background-position:0 -56px;}
.db-nav .parent-list .even a:hover{background-position:0 -342px;}
.db-nav .child-list .odd a{background-position:0 -144px;}
.db-nav .child-list .even a{background-position:0 -173px;}
.db-nav .child-list li a:hover{background-position:0 -387px;}
.db-nav .back-top{display:block; background-position:0 -202px; width:153px; height:89px;}
.db-content{width:980px;}
.db-main .db-sort-box{float:left; margin-bottom:50px; background-color:#f14572; -moz-border-radius:10px; -webkit-border-radius:10px; border-radius:10px;}
.db-sort-box .sort-banner{display:block; width:210px; margin-top:15px; margin-bottom:15px;}
.db-sort-box .fl .sort-banner{margin-left:-10px;}
.db-sort-box .fr .sort-banner{margin-right:-10px;}
.db-sort-box .db-goods{list-style-type:none; margin:0; margin-top:15px; padding:0; clear:both; overflow:hidden; width:776px;}
.db-sort-box .fr .db-goods{margin-right:4px;}
.db-sort-box .fl .db-goods{margin-left:4px;}
.db-goods li{float:left; width:186px; margin-bottom:10px; background-color:#ff507f;}
.db-sort-box .fr .db-goods li{margin-right:7px;}
.db-sort-box .fl .db-goods li{margin-left:8px;}
.db-goods .goods-img{display:block; width:186px; height:186px; background-color:#fff;}
.db-goods .goods-img img{width:186px; height:186px;}
.db-goods .title{color:#fff; font-size:14px; line-height:20px; display:block; width:176px; height:40px; overflow:hidden; margin:5px auto; *padding-top:0; text-decoration:none;}
.db-goods .title:hover{text-decoration:underline;}
.db-goods .bottom{border-top:1px dashed #bbb; width:176px; margin:0 auto; overflow:hidden; clear:both;}
.db-goods .price{font-size:13px; color:#fff; height:50px; line-height:50px;}
.db-goods .price b{color:#fff000; font-size:23px; font-weight:normal;}
.db-goods .price span{color:#fff000; font-size:14px;}
.db-goods .price b b{font-size: 14px;}
.db-goods .buy-btn{display:block; background:url(/static/default/images/topic/btn_icon_11.png) 0 0; width:52px; height:23px; margin-right:5px; margin-top:13px;}
.db-goods .buy-btn:hover{background-position:0 -26px;}
/*.db-footer{background:url(/static/default/images/topic/foot_banner.jpg) repeat center center; width:100%; min-width:1340px; height:282px; margin-top:-30px; margin-bottom:-20px;}
.db-footer a{display:block; width:250px; height:282px; margin:0 auto;}*/
.db-footer{background-color: #cc0e32; border-top: 5px solid #ba172a; border-bottom: 5px solid #ba172a; clear: both; overflow: hidden; height: 90px; margin-bottom: -20px;}
.db-footer .area{position: relative; height: 100px;}
.db-footer .area a{position: absolute; left: 0; top: -5px; width: 1200px; height: 100px;}
</style>
{/literal}
{include file='header.phtml' head=$channel->seo_path}
  {$productModel = BpfCore::getModel('product')}
  <div class="wrapper">
    <div class="db-header"></div>
    <div class="db-main">
      <a href="{url('topic/99m.html')}" target="_blank" class="top-ad">
        <img src="{$tpldir}/images/topic/top_ad.png" alt="顶部广告图"/>
      </a>
      <div class="db-nav abs-nav">
        <div class="title-icon"></div>
        <ul class="parent-list">
          <li><a href="javascript:void(0);">单身告白</a></li>
          <li><a href="javascript:void(0);">宝贝计划</a></li>
          <li><a href="javascript:void(0);">家庭指南</a></li>
          <li><a href="javascript:void(0);">全民必备</a></li>
        </ul>
        <ul class="child-list">
        {$cate = $productModel->getHomeCategories()}
          {if isset($cate) && $cate}
          {foreach $cate as $sa}
          <li>
            <a target="_blank" href="{$sa->link}" title="{$sa->name|escape}"><b>{$sa->name|escape}</b> ></a>
          </li>
          {/foreach}
          {/if}
        </ul>
        <a href="javascript:void(0);" class="back-top"></a>
      </div>
      <div class="db-content">
        <div class="db-sort-box" id="sort1">
          <div class="fl">
            <span class="sort-banner">
              <img src="{$tpldir}/images/topic/banner_01.png" alt="分类宣传图"/>
            </span>
          </div>
          <div class="fr">
            <ul class="db-goods">
              {$conditions.where.status = 1}
              {$conditions.channel = 95}
              {$conditions.orderby = '`updated` DESC'}
              {$conditions.tags = 3542}
              {$productList = $productModel->getProducts($conditions, 1, 8)}
              {if isset($productList) && $productList}
              {foreach $productList as $sa}
              <li>
                <a href="{$sa->link_click}" target="_blank" class="goods-img">
                  <img src="{urlStatic($sa->image_path, 310, 310)}" width="186" height="186" alt="{$sa->title|escape}"/>
                </a>
                <a href="{$sa->link}" target="_blank" class="title" title="{$sa->title|escape}">{$sa->title|escape}</a>
                <div class="bottom">
                  <div class="price fl">
                    <b>{$sa->sell_price|price}</b>
                    <del>{floatval($sa->list_price)}</del>
                  </div>
                  <a href="{$sa->link_click}" target="_blank" class="buy-btn fr"></a>
                </div>
              </li>
              {/foreach}
              {/if}
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div class="db-sort-box" id="sort2">
          <div class="fr">
            <span class="sort-banner">
              <img src="{$tpldir}/images/topic/banner_02.png" alt="分类宣传图"/>
            </span>
          </div>
          <div class="fl">
            <ul class="db-goods">
              {$conditions.tags = 3543}
              {$productList = $productModel->getProducts($conditions, 1, 8)}
              {if isset($productList) && $productList}
              {foreach $productList as $sa}
              <li>
                <a href="{$sa->link_click}" target="_blank" class="goods-img">
                  <img src="{urlStatic($sa->image_path, 310, 310)}" width="186" height="186" alt="{$sa->title|escape}"/>
                </a>
                <a href="{$sa->link}" target="_blank" class="title" title="{$sa->title|escape}">{$sa->title|escape}</a>
                <div class="bottom">
                  <div class="price fl">
                    <b>{$sa->sell_price|price}</b>
                    <del>{floatval($sa->list_price)}</del>
                  </div>
                  <a href="{$sa->link_click}" target="_blank" class="buy-btn fr"></a>
                </div>
              </li>
              {/foreach}
              {/if}
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div class="db-sort-box" id="sort3">
          <div class="fl">
            <span class="sort-banner">
              <img src="{$tpldir}/images/topic/banner_03.png" alt="分类宣传图"/>
            </span>
          </div>
          <div class="fr">
            <ul class="db-goods">
              {$conditions.tags = 3544}
              {$productList = $productModel->getProducts($conditions, 1, 12)}
              {if isset($productList) && $productList}
              {foreach $productList as $sa}
              <li>
                <a href="{$sa->link_click}" target="_blank" class="goods-img">
                  <img src="{urlStatic($sa->image_path, 310, 310)}" width="186" height="186" alt="{$sa->title|escape}"/>
                </a>
                <a href="{$sa->link}" target="_blank" class="title" title="{$sa->title|escape}">{$sa->title|escape}</a>
                <div class="bottom">
                  <div class="price fl">
                    <b>{$sa->sell_price|price}</b>
                    <del>{floatval($sa->list_price)}</del>
                  </div>
                  <a href="{$sa->link_click}" target="_blank" class="buy-btn fr"></a>
                </div>
              </li>
              {/foreach}
              {/if}
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div class="db-sort-box" id="sort4">
          <div class="fr">
            <span class="sort-banner">
              <img src="{$tpldir}/images/topic/banner_04.png" alt="分类宣传图"/>
            </span>
          </div>
          <div class="fl">
            <ul class="db-goods">
              {$conditions.tags = 3545}
              {$productList = $productModel->getProducts($conditions, 1, 12)}
              {if isset($productList) && $productList}
              {foreach $productList as $sa}
              <li>
                <a href="{$sa->link_click}" target="_blank" class="goods-img">
                  <img src="{urlStatic($sa->image_path, 310, 310)}" width="186" height="186" alt="{$sa->title|escape}"/>
                </a>
                <a href="{$sa->link}" target="_blank" class="title" title="{$sa->title|escape}">{$sa->title|escape}</a>
                <div class="bottom">
                  <div class="price fl">
                    <b>{$sa->sell_price|price}</b>
                    <del>{floatval($sa->list_price)}</del>
                  </div>
                  <a href="{$sa->link_click}" target="_blank" class="buy-btn fr"></a>
                </div>
              </li>
              {/foreach}
              {/if}
            </ul>
          </div>
          <div class="clear"></div>
        </div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="db-footer">
      <div class="area">
        {html_ad id="home-7" width="1200" height="100"}
      </div>
    </div>
  </div>

{include file='footer.phtml'}
</body>
{include file='after_body.phtml'}
{literal}
<script type="text/javascript">
/*控制导航单双项显示不同背景*/
$(document).ready(function(){
  $('.db-nav ul li:nth-child(odd)').addClass('odd');
  $('.db-nav ul li:nth-child(even)').addClass('even');
  $('.side_panel').remove();
  $('.side_checkin').remove();
});
/*导航跳滑动固定效果*/
$(document).ready(function(){
  var offsetTop = $('.db-nav').offset().top;
  var offsetRight = ($(document).width()-980)/2-180;
  var stick = function(){
    var scrollTop = $(window).scrollTop();
    if(scrollTop > offsetTop){
      $('.db-nav').removeClass('abs-nav').addClass('fixed-nav').css({'right':offsetRight});
    }else{
      $('.db-nav').removeClass('fixed-nav').addClass('abs-nav').css({'right':'-180px'});
    }
  }
  //运行控制函数
  stick();
  $(window).scroll(function(){
    stick();
  });
});
/*导航主链接缓慢跳转效果*/
$(document).ready(function(){
  $('.back-top').click(function(){
    $('html,body').animate({scrollTop:'0'},400);
  });
  var sort1Top = $('#sort1').offset().top;
  var sort2Top = $('#sort2').offset().top;
  var sort3Top = $('#sort3').offset().top;
  var sort4Top = $('#sort4').offset().top;
  $(".parent-list li:nth-child(1) a").click(function(){
    $('html,body').animate({scrollTop:sort1Top},400);
  });
  $(".parent-list li:nth-child(2) a").click(function(){
    $('html,body').animate({scrollTop:sort2Top},400);
  });
  $(".parent-list li:nth-child(3) a").click(function(){
    $('html,body').animate({scrollTop:sort3Top},400);
  });
  $(".parent-list li:nth-child(4) a").click(function(){
    $('html,body').animate({scrollTop:sort4Top},400);
  });
});
</script>
{/literal}
</html>