{include file='before_body.phtml' title='护肤主会场，提前双11，众多商品任你选_上天天逛逛，还不够吗？'}
<body>
{literal}
<style type="text/css">
html,body{margin:0; padding:0; height:100%;}
body{background-color:#72e3ff; font:12px/1.3 "微软雅黑","宋体",arial,sans-serif; min-width: 1340px;}
a{text-decoration:none;} a:hover{text-decoration:none;}
.sale-list .sale3, .sale-list .sale4, .box .btn{background:url(/static/default/images/topic/hufu_icon.png) no-repeat;}
.big-banner{width:100%; min-width:1340px; height:645px; background:url(/static/default/images/topic/banner.jpg) no-repeat center center;}
.top-sale{width:100%; min-width:1340px; height:215px; background:url(/static/default/images/topic/ad_back.png) no-repeat center center;}
.top-sale .sale-list{background:url(/static/default/images/topic/top_sale.png) no-repeat; width:980px;height:200px; margin:0 auto; position:relative;}
.sale-list a{color:#22a7c4; font-size:14px; display:block; position:absolute;}
.sale-list .sale99{width:300px; height:60px; left:345px; top:0;}
.sale-list .sale1{top:123px; left:90px; width:105px;}
.sale-list .sale2{top:123px; left:378px; width:105px;}
.sale-list .sale1:hover, .sale-list .sale2:hover{color:#3372d9;}
.sale-list .sale3, .sale-list .sale4{color:#fee44e; background-position:-5px -5px; width:96px; height:24px; font-size:12px; line-height:24px; text-align:center;}
.sale-list .sale3{top:135px; left:625px;}
.sale-list .sale4{top:135px; left:865px;}
.sale-list .sale3:hover, .sale-list .sale4:hover{color:#fff;}
.img-sale1{width:76px; height:145px; top:45px; left:7px;}
.img-sale2{width:140px; height:145px; top:45px; left:230px;}
.img-sale3{width:125px; height:122px; top:65px; left:490px;}
.img-sale4{width:125px; height:150px; top:42px; right:122px;}
.step1{background:url(/static/default/images/topic/step1.png) no-repeat center center; height:685px;}
.step2{background:url(/static/default/images/topic/step2.png) no-repeat center center; height:685px;}
.step3{background:url(/static/default/images/topic/step3.png) no-repeat center center; height:685px;}
.step4{background:url(/static/default/images/topic/step4.png) no-repeat center center; height:685px;}
.step5{background:url(/static/default/images/topic/step5.png) no-repeat center center; height:685px;}
.step6{background:url(/static/default/images/topic/step6.png) no-repeat center center; height:822px;}
.box{width:960px; margin:0 auto; position:relative;}
.box > a{display:block; position:absolute;}
.box .m1, .box .m2{position:absolute;}
.m1 a, .m2 a{color:#333;}
.m1 a:hover, .m2 a:hover{color:#3372d9;}
a.btn{display:block; width:106px; height:27px; line-height:27px; color:#fff; font-size:14px; padding-left:35px;}
a.btn:hover{color:#fff; font-weight:bold;}
.m1 .btn{margin-top:75px;}
.m2 .btn{margin-top:20px;}
.more{display:block; width:110px; height:20px; border-radius:10px; color:#fff; text-align:center; line-height:20px; position:absolute;}
.more:hover{font-weight:bold; color:#fff;}
.step1 .btn{background-position:-5px -33px;}
.step2 .btn{background-position:-5px -64px;}
.step3 .btn{background-position:-5px -95px;}
.step4 .btn{background-position:-5px -126px;}
.step5 .btn{background-position:-5px -157px;} 
.step6 .btn{background-position:-5px -187px;}
.step1 .more{background-color:#5bdbfe; top:205px; left:70px;}
.step2 .more{background-color:#a38bd7; top:208px; right:73px;}
.step3 .more{background-color:#91cb00; top:221px; left:68px;}
.step4 .more{background-color:#f34567; top:205px; right:73px;}
.step5 .more{background-color:#6de591; top:208px; left:70px;}
.step6 .more{background-color:#ff77df; top:210px; right:73px;}
.s1-1{top:308px; left:218px;} .s1-1 .btn{margin-left:16px;} .s1-2{top:528px; left:80px;} .s1-2 .btn{margin-left:5px;} .s1-3{top:115px; right:60px;} .s1-3 .btn{margin-left:13px;} .s1-4{top:581px; right:60px;} .s1-4 .btn{margin-left:20px;}
.s2-1{top:75px; left:242px;} .s2-1 .btn{margin-left:25px;} .s2-2{top:290px; left:160px;} .s2-2 .btn{margin-left:25px;} .s2-3{top:518px; left:44px;} .s2-4{top:576px; right:70px;}
.s3-1{top:305px; left:218px;} .s3-1 .btn{margin-left:15px;} .s3-2{top:527px; left:80px;} .s3-2{margin-left:5px;} .s3-3{top:117px; right:55px;} .s3-3 .btn{margin-left:30px;} .s3-4{top:581px; right:55px;} .s3-4 .btn{margin-left:15px;}
.s4-1{top:66px; left:290px;} .s4-1 .btn{margin-left:25px;} .s4-2{top:262px; left:193px;} .s4-2 .btn{margin-left:16px;} .s4-3{top:502px; left:45px;} .s4-3 .btn{margin-left:20px;} .s4-4{top:585px; right:60px;} .s4-4 .btn{margin-left:25px;}
.s5-1{top:310px; left:185px;} .s5-1 .btn{margin-left:50px;} .s5-2{top:528px; left:80px;} .s5-2 .btn{margin-left:5px;} .s5-3{top:117px; right:50px;} .s5-4{top:583px; right:55px;} .s5-4 .btn{margin-left:15px;}
.s6-1{top:61px; left:300px;} .s6-1 .btn{margin-left:15px;} .s6-2{top:261px; left:182px;} .s6-2 .btn{margin-left:25px;} .s6-3{top:496px; left:40px;} .s6-3 .btn{margin-left:15px;} .s6-4{top:581px; right:60px;} .s6-4 .btn{margin-left:25px;}
.menu{position:absolute; right:-140px; top:26px; z-index:5000;}
.menu ul{list-style-type:none; margin:0; padding:10px 0; background-color:#3372d9; width:130px;}
.menu ul li a{display:block; width:130px; height:30px; line-height:30px; color:#fff; font-size:18px; text-align:center;}
.menu ul li a.visitedClass, .menu ul li a.hoverClass{background-color:#b4bcfb;}
.menu ul li a.originColor{background-color:#3372d9;}
.img-s1-1, .img-s1-2, .img-s1-3, .img-s1-4, .img-s2-1, .img-s2-2, .img-s2-3, .img-s2-4, .img-s3-1, .img-s3-2, .img-s3-3, .img-s3-4,
.img-s4-1, .img-s4-2, .img-s4-3, .img-s4-4, .img-s5-1, .img-s5-2, .img-s5-3, .img-s5-4, .img-s6-1, .img-s6-2, .img-s6-3, .img-s6-4{width:170px; height:200px;}
.img-s1-1{top:260px; left:42px;} .img-s1-2{top:465px; left:215px;} .img-s1-3{top:30px; right:235px;} .img-s1-4{top:315px; right:57px;}
.img-s2-1{top:65px; left:60px;} .img-s2-2{top:275px; left:-19px;} .img-s2-3{top:470px; left:188px;} .img-s2-4{top:315px; right:64px;}
.img-s3-1{top:266px; left:35px;} .img-s3-2{top:465px; left:240px;} .img-s3-3{top:30px; right:242px;} .img-s3-4{top:315px; right:57px;}
.img-s4-1{top:33px; left:100px;} .img-s4-2{top:253px; left:16px;} .img-s4-3{top:470px; left:188px;} .img-s4-4{top:315px; right:64px;}
.img-s5-1{top:288px; left:42px;} .img-s5-2{top:465px; left:215px;} .img-s5-3{top:30px; right:218px;} .img-s5-4{top:315px; right:57px;}
.img-s6-1{top:33px; left:100px;} .img-s6-2{top:253px; left:16px;} .img-s6-3{top:470px; left:188px;} .img-s6-4{top:315px; right:64px;}

.footer{margin-top: 0}
</style>
{/literal}
{include file='header.phtml' head=$channel->seo_path}

  <div class="wrapper">
    <div class="header">
      <div class="big-banner"></div>
      <div class="top-sale">
        <div class="sale-list">
          <a href="http://www.ttgg.com/topic/99m.html" target="_blank" title="9块9" class="sale99"></a>
          <a href="http://www.ttgg.com/item/2014100154d11e.html" target="_blank" title="滋润保湿美白嫩手护手霜" class="img-sale1"></a>
          <a href="http://www.ttgg.com/item/2014100154d11e.html" target="_blank" class="sale1">滋润保湿美白嫩手护手霜</a>
          <a href="http://www.ttgg.com/item/2014100154d2ca.html" target="_blank" title="卡哇伊滋润保湿护手霜" class="img-sale2"></a>
          <a href="http://www.ttgg.com/item/2014100154d2ca.html" target="_blank" class="sale2">卡哇伊滋润保湿护手霜</a>
          <a href="http://www.ttgg.com/item/2014090154cd21.html" target="_blank" title="月影全效橄榄油" class="img-sale3"></a>
          <a href="http://www.ttgg.com/item/2014090154cd21.html" target="_blank" class="sale3">查看商品详情》</a>
          <a href="http://www.ttgg.com/item/2014100154d1bb.html" target="_blank" title="草本护手霜 嫩白手部护理套装 滋润保湿美白去角质手膜腊" class="img-sale4"></a>
          <a href="http://www.ttgg.com/item/2014100154d1bb.html" target="_blank" class="sale4">查看商品详情》</a>
        </div>
      </div>
    </div>
    <div class="content">
      <div class="step1">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s1-1 m1">
            <a href="http://www.ttgg.com/item/2014090154cc93.html" target="_blank">兰可欣红石榴女士套装</a>
            <a href="http://www.ttgg.com/product/click/2014090154cc93.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014090154cc93.html" target="_blank" title="兰可欣红石榴女士套装" class="img-s1-1"></a>
          <div class="s1-2 m1">
            <a href="http://www.ttgg.com/item/2014100154d023.html" target="_blank">茶花蜂胶润白补水洁面膏</a>
            <a href="http://www.ttgg.com/product/click/2014100154d023.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d023.html" target="_blank" title="茶花蜂胶润白补水洁面膏" class="img-s1-2"></a>
          <div class="s1-3 m1">
            <a href="http://www.ttgg.com/item/2014090154ce6d.html" target="_blank">温碧泉补水保湿化妆品套盒</a>
            <a href="http://www.ttgg.com/product/click/2014090154ce6d.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014090154ce6d.html" target="_blank" title="温碧泉补水保湿化妆品套盒" class="img-s1-3"></a>
          <div class="s1-4 m2">
            <a href="http://www.ttgg.com/item/2014110154d8c5.html" target="_blank">DaisyGloria 美白保湿洁面乳</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8c5.html" target="_blank" class="btn">立即购买</a>
          </div>        
          <a href="http://www.ttgg.com/item/2014110154d8c5.html" target="_blank" title="DaisyGloria 美白保湿洁面乳" class="img-s1-4"></a>
          <div class="menu">
            <ul>
              <li><a href="javascript:void(0);" class="originColor">洁面</a></li>
              <li><a href="javascript:void(0);" class="originColor">化妆水</a></li>
              <li><a href="javascript:void(0);" class="originColor">精华</a></li>
              <li><a href="javascript:void(0);" class="originColor">眼部护理</a></li>
              <li><a href="javascript:void(0);" class="originColor">面霜</a></li>
              <li><a href="javascript:void(0);" class="originColor">面膜</a></li>
              <li><a href="javascript:void(0);" class="originColor">返回顶部</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="step2">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s2-1 m1">
            <a href="http://www.ttgg.com/item/2014100154d767.html" target="_blank">水芝澳海洋保湿滋润护手</a>
            <a href="http://www.ttgg.com/product/click/2014100154d767.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d767.html" target="_blank" title="水芝澳海洋保湿滋润护手" class="img-s2-1"></a>
          <div class="s2-2 m1">
            <a href="http://www.ttgg.com/item/2014100154d76d.html" target="_blank">自然堂雪域冰肌水保湿爽肤水</a>
            <a href="http://www.ttgg.com/product/click/2014100154d76d.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d76d.html" target="_blank" title="自然堂雪域冰肌水保湿爽肤水" class="img-s2-2"></a>
          <div class="s2-3 m1">
            <a href="http://www.ttgg.com/item/2014100154d00c.html" target="_blank">芦荟胶爽肤美白保湿套装</a>
            <a href="http://www.ttgg.com/product/click/2014100154d00c.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d00c.html" target="_blank" title="芦荟胶爽肤美白保湿套装" class="img-s2-3"></a>
          <div class="s2-4 m2">
            <a href="http://www.ttgg.com/item/2014090154cd61.html" target="_blank">韩洛依正品保湿套装</a>
            <a href="http://www.ttgg.com/product/click/2014090154cd61.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014090154cd61.html" target="_blank" title="韩洛依正品保湿套装" class="img-s2-4"></a>
        </div>
      </div>
      <div class="step3">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s3-1 m1">
            <a href="http://www.ttgg.com/item/2014090154cd2e.html" target="_blank">圣娜姿黄金赋活精华液</a>
            <a href="http://www.ttgg.com/product/click/2014090154cd2e.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014090154cd2e.html" target="_blank" title="圣娜姿黄金赋活精华液" class="img-s3-1"></a>
          <div class="s3-2 m1">
            <a href="http://www.ttgg.com/item/2014110154d8d2.html" target="_blank">保湿芳疗淡斑单方护肤精油</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8d2.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8d2.html" target="_blank" title="保湿芳疗淡斑单方护肤精油" class="img-s3-2"></a>
          <div class="s3-3 m1">
            <a href="http://www.ttgg.com/item/2014100154d756.html" target="_blank">欧珀莱均衡保湿水润感应精华露</a>
            <a href="http://www.ttgg.com/product/click/2014100154d756.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d756.html" target="_blank" title="欧珀莱均衡保湿水润感应精华露" class="img-s3-3"></a>
          <div class="s3-4 m2">
            <a href="http://www.ttgg.com/item/2014100154d67e.html" target="_blank">玉兰油水感透白净瑕精华露</a>
            <a href="http://www.ttgg.com/product/click/2014100154d67e.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d67e.html" target="_blank" title="玉兰油水感透白净瑕精华露" class="img-s3-4"></a>
        </div>
      </div>
      <div class="step4">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s4-1 m1">
            <a href="http://www.ttgg.com/item/2014100154d763.html" target="_blank">保湿滋养滋润三件套</a>
            <a href="http://www.ttgg.com/product/click/2014100154d763.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d763.html" target="_blank" title="保湿滋养滋润三件套" class="img-s4-1"></a>
          <div class="s4-2 m1">
            <a href="http://www.ttgg.com/item/2014110154d8cd.html" target="_blank">金桂花淡化黑眼圈细纹眼膜</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8cd.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8cd.html" target="_blank" title="金桂花淡化黑眼圈细纹眼膜" class="img-s4-2"></a>
          <div class="s4-3 m1">
            <a href="http://www.ttgg.com/item/2014100154d2c9.html" target="_blank">韩洛依瞬时修复紧致眼霜</a>
            <a href="http://www.ttgg.com/product/click/2014100154d2c9.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d2c9.html" target="_blank" title="韩洛依瞬时修复紧致眼霜" class="img-s4-3"></a>
          <div class="s4-4 m2">
            <a href="http://www.ttgg.com/item/2014100154d11f.html" target="_blank">紧致补水保湿脂肪粒走珠眼霜</a>
            <a href="http://www.ttgg.com/product/click/2014100154d11f.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d11f.html" target="_blank" title="紧致补水保湿脂肪粒走珠眼霜" class="img-s4-4"></a>
        </div>
      </div>
      <div class="step5">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s5-1 m1">
            <a href="http://www.ttgg.com/item/2014110154d8cc.html" target="_blank">DaisyGloria 蜗牛精华修复霜</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8cc.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8cc.html" target="_blank" title="小蜜蜂牛奶美白去角质护手霜" class="img-s5-1"></a>
          <div class="s5-2 m1">
            <a href="http://www.ttgg.com/item/2014100154d21b.html" target="_blank">雅丽洁嫩白去角质手部护手霜</a>
            <a href="http://www.ttgg.com/product/click/2014100154d21b.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d21b.html" target="_blank" title="雅丽洁嫩白去角质手部护手霜" class="img-s5-2"></a>
          <div class="s5-3 m1">
            <a href="http://www.ttgg.com/item/2014100154d018.html" target="_blank">韩洛依男士护肤套装</a>
            <a href="http://www.ttgg.com/product/click/2014100154d018.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d018.html" target="_blank" title="韩洛依男士护肤套装" class="img-s5-3"></a>
          <div class="s5-4 m2">
            <a href="http://www.ttgg.com/item/2014090154ce6e.html" target="_blank">梵洁诗玫瑰保湿护肤套装</a>
            <a href="http://www.ttgg.com/product/click/2014090154ce6e.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014090154ce6e.html" target="_blank" title="梵洁诗玫瑰保湿护肤套装" class="img-s5-4"></a>
        </div>
      </div>
      <div class="step6">
        <div class="box">
          <a href="http://www.ttgg.com/cate/meizhuang.html" target="_blank" class="more">点击查看更多>></a>
          <div class="s6-1 m1">
            <a href="http://www.ttgg.com/item/2014110154d8c7.html" target="_blank">美白洗补水抗皱淡斑免洗面膜</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8c7.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8c7.html" target="_blank" title="美白洗补水抗皱淡斑免洗面膜" class="img-s6-1"></a>
          <div class="s6-2 m1">
            <a href="http://www.ttgg.com/item/2014100154d28b.html" target="_blank">京润珍珠纳米珍珠粉面膜</a>
            <a href="http://www.ttgg.com/product/click/2014100154d28b.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014100154d28b.html" target="_blank" title="京润珍珠纳米珍珠粉面膜" class="img-s6-2"></a>
          <div class="s6-3 m1">
            <a href="http://www.ttgg.com/item/2014110154d8c8.html" target="_blank">美白滋润蚕丝隐形面膜</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8c8.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8c8.html" target="_blank" title="美白滋润蚕丝隐形面膜" class="img-s6-3"></a>
          <div class="s6-4 m2">
            <a href="http://www.ttgg.com/item/2014110154d8cb.html" target="_blank">DaisyGloria 保加利亚玫瑰面膜</a>
            <a href="http://www.ttgg.com/product/click/2014110154d8cb.html" target="_blank" class="btn">立即购买</a>
          </div>
          <a href="http://www.ttgg.com/item/2014110154d8cb.html" target="_blank" title="DaisyGloria 保加利亚玫瑰面膜" class="img-s6-4"></a>
        </div>
      </div>
    </div>
  </div>

{include file='footer.phtml'}
</body>
{include file='after_body.phtml'}
{literal}

<script type="text/javascript">
$(document).ready(function() {
  $('.side_panel').remove();
  $('.side_checkin').remove();
  //菜单悬停
  var menuTop = $('.menu').offset().top;
  var fxdRight = parseInt(($(document).width() - 960)/2 - 140);
  var stick = function() {
    var scrollTop = $(window).scrollTop();
    if(scrollTop >= menuTop) {
      $('.menu').css({ 'position':'fixed', 'right':fxdRight });
    } else {
      $('.menu').css({ 'position':'absolute', 'right':'-140px' });
    }
  }
  stick();
  $(window).scroll(function() {
    stick();
  });
  //菜单项缓慢跳转
  var step1Top = $('.step1').offset().top;
  var step2Top = $('.step2').offset().top;
  var step3Top = $('.step3').offset().top;
  var step4Top = $('.step4').offset().top;
  var step5Top = $('.step5').offset().top;
  var step6Top = $('.step6').offset().top;
  $('.menu ul li:nth-child(7) a').click(function() {
    $('html,body').animate({ scrollTop : 0 }, 400);
  });
  $('.menu ul li:nth-child(1) a').click(function() {
    $('html,body').animate({ scrollTop : step1Top }, 400);
  });
  $('.menu ul li:nth-child(2) a').click(function() {
    $('html,body').animate({ scrollTop : step2Top }, 400);
  });
  $('.menu ul li:nth-child(3) a').click(function() {
    $('html,body').animate({ scrollTop : step3Top }, 400);
  });
  $('.menu ul li:nth-child(4) a').click(function() {
    $('html,body').animate({ scrollTop : step4Top }, 400);
  });
  $('.menu ul li:nth-child(5) a').click(function() {
    $('html,body').animate({ scrollTop : step5Top }, 400);
  });
  $('.menu ul li:nth-child(6) a').click(function() {
    $('html,body').animate({ scrollTop : step6Top }, 400);
  });
  //菜单项点击变色
  $('.menu ul li a').click(function() {
    $(this).addClass('visitedClass').remove('originColor');
    $(this).parent().siblings().find('a').remove('visitedClass');
  });
  $('.menu ul li a').hover(function() {
    $(this).addClass('hoverClass').removeClass('originColor');
  }, function() {
    if(!$(this).is('.visitedClass')) {
      $(this).addClass('originColor').removeClass('hoverClass');
    }
  });
  //滚动时菜单变色
  var c = parseInt($(window).height()/2); //取得浏览器高度一半，使得菜单项到中央时切换。
  var colorListener = function() {
    var scrollTop = $(window).scrollTop() + c;
    if(scrollTop < step2Top) {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(1) a').addClass('visitedClass').removeClass('originColor');
    } else if(scrollTop < step3Top) {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(2) a').addClass('visitedClass').removeClass('originColor');
    } else if(scrollTop < step4Top) {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(3) a').addClass('visitedClass').removeClass('originColor');
    } else if(scrollTop < step5Top) {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(4) a').addClass('visitedClass').removeClass('originColor');
    } else if(scrollTop < step6Top) {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(5) a').addClass('visitedClass').removeClass('originColor');
    } else {
      $('.menu ul li a').addClass('originColor').removeClass('visitedClass');
      $('.menu ul li:nth-child(6) a').addClass('visitedClass').removeClass('originColor');
    }
  }
  colorListener();
  $(window).scroll(function() {
    colorListener();
  });
});
</script>
{/literal}
</html>