{include file='before_body.phtml' title='天天逛逛独家优惠，天天送集分宝9.9包邮20元封顶秒杀在天天逛逛'}
	<body>
		<div id="wrapper">
			<div class="scroller">
				<header>
					<h1>{$channel->title}</h1>
					<a class="back" href="javascript:window.history.back();"></a>
				</header>
				<nav class="title-bar">
          <ul class="all">
            <li>
              <a href="javascript:void(0);" id="drop">
                <span>全部<i class="arrow-down"></i></span>
              </a>
              <div class="dropdown-menu" id="dropMemu">
                <i class="arrow-up"></i>
                <ul class="small-cate">
                  <li>
                    <a href="">全部</a>
                  </li>
{if isset($cates) && $cates}
{foreach $cates as $cate}
                  <li><a href="javascript:void(0);" rel="nofollow" isrel="{$channelId|default:0}" iscid="{$cate->cid|default:0}">{$cate->name|escape}</a></li>
{/foreach}

{/if} 
                </ul>
              </div>
            </li>
          </ul>
          <ul class="recent-select">
            <li>
              <a href="javascript:void(0);" rel="nofollow" isrel="hot">热门</a>
            </li>
            <li>
              <a href="javascript:void(0);" rel="nofollow" isrel="new">最新</a>
            </li>
          </ul>
					<div class="clear"></div>
				</nav>
				<section class="deals">
  <div id="cateContent">
    <div class="content-spinner"><i class="icon-spinner icon-spin"></i> 正在加载中...</div>
  </div>
				</section>
				<footer>
					<a id="backTop" href="javascript:void(0);">
						<i></i>
					</a>
				</footer>
			</div>
		</div>

{include file='after_body.phtml'}
<script type="text/javascript">
$(document).ready(function() {
	//菜单显隐
	$('#drop').click(function() {
		$('#dropMemu').toggle();
	});
});
$(document).ready(function() {
  /**产品列表**/
{if isset($channelId) && $channelId}
  var url, is_id, sort = 'new', page = 1, is_cid;
  var load = function(page, id, sort, is_cid) {
    if (typeof id !== 'undefined') {
      url = "{url('product/postChannel/')}" + id;
    } else {
      url = "{url('product/postChannel/'|cat:$channelId)}";
    }
    if (typeof page !== 'undefined') {
      url += '/' + page;
    }
    if (typeof sort !== 'undefined') {
      url += '/' + sort;
    }
    if (typeof is_cid !== 'undefined') {
      url += '/' + is_cid;
    }
    $('#cateContent').load(url, function(date) {
      $('.content-spinner').remove();
      $(this).html(date);
    });
  }
  load();

  $('#cateContent').delegate('.tc a', 'click', function() {
    $('html,body').animate({ scrollTop : '125px'}, 200);
    var id, is_id = $('[name="id"]').val();
    page = parseInt($(this).attr('rel'), 10);
    load(page, is_id, sort, is_cid);
  });
  $('.small-cate a').click(function(){
    is_id = parseInt($(this).attr('isrel'), 10);
    is_cid = $(this).attr('iscid');
    page = 1;
    $(this).parent().addClass("selected").siblings().removeClass();
    load(1, is_id, sort, is_cid);
  });
  $('.recent-select a').click(function(){
    if (!is_id) {
      is_id = undefined;
    };
    $(this).parent().addClass("selected").siblings().removeClass();
    sort = $(this).attr('isrel');
    load(page, is_id, sort, is_cid);
  });
{/if}
});
</script>
	</body>
</html>