{include file='admin/before_body.phtml' title='评论列表'}

<style type="text/css">
.tablecss {
width: 450px;
overflow : hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
word-wrap: break-word;
}
</style>
<body>
{include file='admin/header.phtml'}
<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">
  {include file='admin/sidebar.phtml' navigation='product_view'}
  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="{url('admin/comment/')}">评论管理</a></li>
          <li class="current">评论列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      {if $actionname=="usercom"}
      <div class="row">
        <div class="col-md-12">
          <div class="form-group" id="nestable_list_menu">
            <a href="{url('admin/user/')}" class="btn btn-primary">返回用户列表</a>
          </div>
        </div>
      </div>
      {/if}


      <div class="row">
      <div class="col-md-12">
       <div class="widget box">
        <div class="widget-content no-padding">

         <div class="row">
          <div class="dataTables_header clearfix">
            <div class="col-md-5">
                <form method="get" action="{url('admin/comment/search')}" id="form1">
                <div class="input-group">
                 <input type="text" class="form-control" value="{$seakey|default:""}" placeholder="评论搜索关键词" name="keyword"/>
                 <span class="input-group-addon"><i onclick="document.getElementById('form1').submit();" style="cursor:pointer;" class="icon-search"></i></span>
               </div>
               </form>
            </div>
            <div class="col-md-7">
              <div class="dataTables_paginate paging_bootstrap">
              {if $actionname=="search"}
            {html_pagination page="$curPage" rows="$rows" count="$total" url="{url('admin/comment/'|cat:$actionname|cat:'?page=%page%&sort='|cat:$option|cat:'&keyword='|cat:$seakey)}"}
           {elseif $actionname=="index"}
            {html_pagination page="$page" rows="$rows" count="$total" url="{url('admin/comment/index'|cat:'?page=%page%&sort='|cat:$option)}"}
            {/if}
              </div>
            </div>
           </div>
           </div>

          <form id="myForm" action="{url('admin/comment/batch')}" method="POST" style="margin:0">
         <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
          <thead>
           <tr>
            <th class="checkbox-column"> <input type="checkbox" class="uniform" /> </th>
            <!-- <th> 商品名称 </th>  -->
            <th>评论内容</th>
            <th width="80"> 评论人</th>
            <th width="160" class="sorting_asc"> <a href="javascript:void(0)" id="comTime" onclick="changeFun('comTime')">评论时间 </a><span id="com"></span></th>
            <th width="160" class="sorting_desc"> <a href="javascript:void(0)" id="last_reply_time" onclick="changeFun('last_reply_time')">回复时间</a><span id="reply"></span></th>
            <th width="70"> 状态 </th>
            <th width="70" > 操作 </th>
           </tr>
          </thead>
          <tbody>
          {if isset($comments) && $comments}
          {foreach $comments as $comment}
           <tr>
            <td class="checkbox-column"> <input type="checkbox" class="uniform" name="cid[]" value="{$comment->cid}"/> </td>
            <td><div class="tablecss">{$comment->body|escape|nl2br}</div></td>
            <td>{if isset($critics[$comment->uid])}{$critics[$comment->uid]->username|escape}{/if}</td>
            <td>{$comment->created|date_format:'Y-m-d G:i:s'}</td>
            <td>{$comment->last_reply_time|date_format:'Y-m-d G:i:s'}</td>
            <td>
              {if $comment->status == 1}
              <span class="label label-success">有效</span>
              {else}<span class="label label-danger">已禁用</span>
              {/if}
            </td>
            <td class="align-center">
              <span class="btn-group">
                <a href="javascript:void(0)" class="bs-tooltip btn-reply" title="" data-original-title="回复" id="btn-reply" rel="{$comment->cid}"><i class="icon-reply"></i></a>&nbsp;
                <a href="{url('admin/comment/edit?id='|cat:$comment->cid)}" class="bs-tooltip" data-original-title="修改"><i class="icon-pencil"></i></a>&nbsp;
                <a href="{url('admin/comment/delete?id='|cat:$comment->cid)}" class="bs-tooltip confirm-dialog" data-original-title="删除"><i class="icon-trash"></i></a>
              </span>
          </td>
           </tr>
           {/foreach}
           {else}
           <tr><td colspan="8" class="align-center">没有内容</td></tr>
           {/if}
          </tbody>
         </table>
         <div class="table-footer">
          <div class="col-md-6">
            <div class="table-actions">
              <select name="status" class="select2" id="mySelect" data-minimum-results-for-search="-1">
                <option value="-1">选择需要操作</option>
                <option value="1">启用选中</option>
                <option value="0">禁用选中</option>
                <option value="2">删除选中</option>
              </select>
            </div>
          </div>
          <div class="col-md-6">
           <ul class="pagination">
            {if $actionname=="search"}
            {html_pagination page="$curPage" rows="$rows" count="$total" url="{url('admin/comment/'|cat:$actionname|cat:'?page=%page%&sort='|cat:$option|cat:'&keyword='|cat:$seakey)}"}
           {elseif $actionname=="index"}
            {html_pagination page="$page" rows="$rows" count="$total" url="{url('admin/comment/index'|cat:'?page=%page%&sort='|cat:$option)}"}
            {elseif $actionname=="usercom"}
            {html_pagination page="$page" rows="$rows" count="$total" url="{url('admin/comment/usercom'|cat:'?page=%page%&sort='|cat:$option|cat:'&id='|cat:{$userid})}"}
            {/if}
           </ul>
          </div>
         </div>
       </form>
        </div>
       </div>
      </div>
     </div>

      <!-- /end -->
    </div>
  </div>
</div>
</body>
{include file='admin/after_body.phtml'}
<script type="text/javascript">
function changeFun(option){
  {if $seakey!=null}
  window.location.href = '/admin/comment/search?sort='+option+'&page=1&keyword={$seakey}';
  {else}
  window.location.href = '/admin/comment/index?sort='+option+'&page=1';
  {/if}
}
window.onload=function()//用window的onload事件，窗体加载完毕的时候
{
   var reg = new RegExp("(^|&)sort=([^&]*)(&|$)","i");
   var r = window.location.search.substr(1).match(reg);
   if(r!=null){
     if(r.indexOf('comTime')!=null && r.indexOf('comTime')!=-1){
      document.getElementById("comTime").style.display = "none";
      document.getElementById("com").innerHTML="评论时间";
     }else{
      document.getElementById("last_reply_time").style.display = "none";
      document.getElementById("reply").innerHTML="回复时间";
     }
   }
}
</script>
<script type="text/javascript">
$(document).ready(function() {
  $('#mySelect').change(function(){
    if($('#mySelect').val()==2){
      bootbox.dialog({
      message: "删除后将不可恢复，请谨慎操作！！",
      buttons: {
        danger: {
          label: "确认",
          className: "btn-danger",
          callback: function() {
            $('#myForm').submit();
          }
        },
        main: {
          label: "返回",
          className: "btn",
          callback: function() {}
        }
      }
      })
    }else{
      $('#myForm').submit();
    }
  });
});
</script>
<script type="text/javascript">
$('#selectsort').change(function() {
  {if $seakey!=null}
  window.location.href = '/admin/comment/{$actionname}?sort='+$('#selectsort').val()+'&page=1&keyword={$seakey}';
  {else}
  window.location.href = '/admin/comment/index?sort='+$('#selectsort').val()+'&page=1';
  {/if}
});
$("a.btn-reply").click(function(b) {
  var cid=this.rel;
  b.preventDefault();
  bootbox.dialog({
      message: '回复内容<BR /><BR /><textarea rows="4" cols="5" name="textarea" class="form-control" id="dialogshow"></textarea>',
      buttons: {
        danger: {
          label: "确认",
          className: "btn-danger",
          callback: function() {
            // alert(url);
            post($("#dialogshow").val(),cid);
            window.location.href = "/admin/comment";
          }
        },
        main: {
          label: "返回",
          className: "btn",
          callback: function() {}
        }
      }
  })
});
function post(content,cid) {
   $.ajax({
    type: "POST",
    async: false,
    data:{ "replycontent":content,"cid":cid },
    url : "/admin/comment/reply",
    dataType : 'jsonp',
    success : function(data){
    },
    error:function(XMLHttpRequest, textStatus, errorThrown){
    }
  });
}
</script>

</html>
