{include file='before_body.phtml' title=$category->name}
<body>
<style type="text/css">
.content-spinner{ clear: both; overflow: hidden; text-align: center; font-size: 26px; padding: 90px 0; color:#666; }
</style>
{include file='header.phtml'}
<div class="area">
  <div class="title_un2">
    <div class="heading">
      <strong>{$category->name}</strong>
    </div>
{if isset($childCates) && $childCates}
    <ul class="small-cate">
{foreach $childCates as $cate}
      <li><a href="javascript:void(0);" rel="nofollow" isrel="{$cate->cid|default:0}">{$cate->name|escape}</a></li>
{/foreach}
      <li class="selected"><a href="javascript:void(0);" rel="nofollow" isrel="{$categoryId|default:0}">全部</a></li>
    </ul>
{/if}
    <ul class="recent-select">
      <li><a href="javascript:void(0);" rel="nofollow" isrel="hot">热门</a></li>
      <li class="selected"><a href="javascript:void(0);" rel="nofollow" isrel="new">最新</a></li>
    </ul>
    <div class="clear"></div>
  </div>
  <!--产品列表 start-->
  <div id="cateContent">
    <div class="content-spinner"><i class="icon-spinner icon-spin"></i> 正在加载中...</div>
  </div>
  <!--产品列表 end-->
  {html_ad id="home-7" width="1200" height="90"}
</div>
<!--页面左侧导航 start-->
<div class="side-panel left-panel">
  <div class="tab-content">
    <ul>
      <li class="tab-index">
        <a href="{url('')}"><i></i></a>
        <div class="tab-tip">
          <a href="{url('')}">首页</a>
        </div>
      </li>
{if isset($cates) && $cates}
{foreach $cates as $cate}
{if $category->name == $cate->name}
      <li class="cur">
{else}
      <li>
{/if}
        <a href="{$cate->link}"><i class="{$cate->seo_path}"></i></a>
        <div class="tab-tip">
          <a href="{$cate->link}">{$cate->name|escape}</a>
        </div>
      </li>
{/foreach}
{/if}
    </ul>
  </div>
</div>
<!--页面左侧导航 end-->
{include file='footer.phtml'}
{include file='after_body.phtml'}
<script type="text/javascript">
$(document).ready(function() {
  /**产品列表**/
{if isset($categoryId) && $categoryId}
  var url, is_id, sort, page = 1;
  var load = function(page, id, sort) {
    if (typeof id !== 'undefined') {
      url = "{url('product/postCate/')}" + id;
    } else {
      url = "{url('product/postCate/'|cat:$categoryId)}";
    }
    if (typeof page !== 'undefined') {
      url += '/' + page;
    }
    if (typeof sort !== 'undefined') {
      url += '/' + sort;
    }
    $('#cateContent').load(url, function(date) {
      $('.content-spinner').remove();
      $(this).html(date);
    });
  }
  load();

  $('#cateContent').delegate('.tc a', 'click', function() {
    $('html,body').animate({ scrollTop : '125px'}, 200);
    var id, is_id = $('[name="id"]').val();
    page = parseInt($(this).attr('rel'), 10);
    load(page, is_id, sort);
  });
  $('.small-cate a').click(function(){
    is_id = parseInt($(this).attr('isrel'), 10);
    page = 1;
    $(this).parent().addClass("selected").siblings().removeClass();
    load(1, is_id, sort);
  });
  $('.recent-select a').click(function(){
    if (!is_id) {
      is_id = undefined;
    };
    $(this).parent().addClass("selected").siblings().removeClass();
    sort = $(this).attr('isrel');
    load(page, is_id, sort);
  });
{/if}
  /**分类页导航条滑动悬停效果**/
  var titleOffsetTop = $('.title_un2').offset().top;
  function fxd() {
    var scrollTop = $(window).scrollTop();
    if(scrollTop >= titleOffsetTop) {
      $('.title_un2').addClass('fxd');
    } else {
      $('.title_un2').removeClass('fxd');
    }
  }
  //触发悬停
  fxd();
  $(window).scroll(function() {
    fxd();
  });
});
</script>
</body>
</html>
