{include file='admin/before_body.phtml' title='反馈列表'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='user_view'}
  {$type = $smarty.get.type|default:''}
  {$opinion = $smarty.get.opinion|default:''}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i>用户管理</li>
          <li class="current">反馈列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}

      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-content no-padding">
              <form action="{url('admin/user/feedback')}" method="GET" id="form1" style="margin:0">
              <div class="row">
                <div class="dataTables_header clearfix">
                  <div class="col-md-3">
                     <div class="input-group">
                      <input type="text" name="type" value="{$type}" placeholder="反馈类型.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                     </div>
                  </div>
                  <div class="col-md-3">
                     <div class="input-group">
                      <input type="text" name="opinion" value="{$opinion}" placeholder="反馈内容过滤.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                     </div>
                  </div>

                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/user/feedback?page=%page%&type='|cat:$type|cat:'&opinion='|cat:$opinion)}"}
                    </div>
                  </div>
                </div>
              </div>
                <!-- <input type="submit"  style="display:none"> -->
              </form>
              <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
                <thead>
                  <tr>
                    <th width="80">反馈序号</th>
                    <th width="80">反馈类型</th>
                    <th>反馈意见</th>
                    <th width="200">联系方式</th>
                    <th width="120">反馈时间</th>
                    <th width="80">操作</th>
                  </tr>
                </thead>
                <tbody>
                  {if isset($feedbackList) && $feedbackList}
                    {foreach $feedbackList as $sa}
                      <tr>
                        <td>{$sa->fid}</td>
                        <td>{$sa->type}</td>
                        <td>{$sa->opinion|escape}</td>
                        <td>{$sa->contact}</td>
                        <td>{$sa->created|date_format:'Y-m-d G:i:s'}</td>
                        <td >
                          <a href="{url('admin/user/feedbackDelete?id='|cat:$sa->fid)}" class="bs-tooltip confirm-dialog" data-original-title="删除反馈"><i class="icon-trash"></i></a>
                        </td>
                      </tr>
                    {/foreach}
                  {/if}
                </tbody>
              </table>
              <div class="row">
                <div class="table-footer">
                  <div class="col-md-6">
                  </div>
                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/user/feedback?page=%page%&type='|cat:$type|cat:'&opinion='|cat:$opinion)}"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>

{include file='admin/after_body.phtml'}
<script type="text/javascript">

</script>
</html>