{include file='admin/before_body.phtml' title='权限列表'}

<body>
{include file='admin/header.phtml'}
<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">
  {include file='admin/sidebar.phtml' navigation='user_view'}
  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="#">用户管理</a></li>
          <li class="current"><a href="#" title="">权限列表</a></li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      <div class="row">
      <div class="col-md-12">
       <div class="widget">
        <div class="page-header"></div>
        <div class="widget-content">
        <form class="form-horizontal row-border" id="validate" action="{url('admin/role/permission')}" method="POST">
        <table class="table table-striped table-bordered table-checkable table-highlight-head table-no-inner-border table-hover">
          <thead>
           <tr>
            <th></th>
            <!--all roles-->
            {foreach $roles as $role}
            {if $role->rid==1}
            {continue}
            {/if}
            <th class="align-center">{$role->name|escape}</th>
            {/foreach}
           </tr>

          </thead>
          <!--show permission-->
          <tbody>
            {foreach $allpermission as $key => $perarray }
              <tr><td colspan="{$roles|count+1}"><strong>{$key}</strong></td></tr>
              {foreach $perarray as $permission => $pername }
              <tr>
                <td class="align-center">{$pername}</td>
              {foreach $roles as $role}
              {if $role->rid==1}
              {continue}
              {/if}
              <td class="align-center">
                <input type="checkbox"{if isset($rolesPer[$role->rid]) && in_array($permission, $rolesPer[$role->rid])} checked="checked"{/if} name="permission[{$role->rid}][{$permission}]" class="">
              </td>
              {/foreach}
              </tr>
              {/foreach}
            {/foreach}
          </tbody>
        </table>
        <div class="row">
          <div class="dataTables_footer clearfix">
            <div class="col-md-12">
              <input type="submit" value="保存提交" class="btn btn-primary">
              <input type="reset" value="全部重置" class="btn">
            </div>
          </div>
        </div>
        </form>
        </div>
       </div>
      </div>
     </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>
{include file='admin/after_body.phtml'}
<script>

</script>
</html>
