{include file='admin/before_body.phtml' title='自动设置头像'}
<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='user_view'}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="{url('admin/user/')}">用户管理</a></li>
          <li class="current">自动设置头像</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="form-group" id="nestable_list_menu">
            <a href="javascript:void(0);" class="btn btn-primary">开始设置</a>
          </div>
        </div>
      </div>
    
      <div class="row">
      <div class="col-md-12">
         <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
          <thead>
           <tr>
            <th>ID</th>
            <th>昵称</th>
            <th width="70">状态</th>
           </tr>
          </thead>
          <tbody id="avatar">
          </tbody>
         </table>
      </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>

{include file='admin/after_body.phtml'}
<script type="text/javascript">
$(document).ready(function(e) {
  $('#nestable_list_menu > a').click(function() {
    $('#nestable_list_menu').html(''); // 防止手贱
    var avatar = $('#avatar') , count = {$count};
    for (var i = count - 1; i >= 0; i--) {
      $.post('{url("admin/user/setAvatar")}', function(data) {
        var content = [
          '<tr>',
          '<td>' + data.uid + '</td>',
          '<td>' + data.nickname + '</td>',
          '<td>' + data.status + '</td>',
          '<tr>'
        ].join('');
        avatar.append(content);
      }, 'json');
    };
  });
});
</script>
</body>
</html>
