{include file='admin/before_body.phtml' title='行为列表'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='user_view'}
  {$op = $smarty.get.op|default:''}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i>用户管理</li>
          <li class="current">行为列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}

      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-content no-padding">
              <form action="{url('admin/user/usersScoresLogs')}" method="GET" id="form1" style="margin:0">
              <div class="row">
                <div class="dataTables_header clearfix">
                  <div class="col-md-3">
                    <div class="input-group">
                      <input type="text" name="op" value="{$op}" placeholder="事件对象.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                    </div>
                  </div>
                  <div class="col-md-9">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/user/usersScoresLogs?page=%page%&op='|cat:$op)}"}
                    </div>
                  </div>
                </div>
              </div>
               
              </form>
              <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
                <thead>
                  <tr>
                    <th width="80">日志序号</th>
                    <th width="100">用户ID</th>
                    <th width="120">事件</th>
                    <th>事件内容</th>
                    <th width="100">分数变化</th>
                    <th width="200">日志时间</th>
                  </tr>
                </thead>
                <tbody>
                  {if isset($usersScoresLogsList) && $usersScoresLogsList}
                    {foreach $usersScoresLogsList as $sa}
                      <tr>
                        <td>{$sa->lid}</td>
                        <td>{$sa->uid}</td>
                        <td>{$sa->op}</td>
                        <td>{$sa->body|escape}</td>
                        <td>{$sa->scores}</td>
                        <td>{$sa->created|date_format:'Y-m-d G:i:s'}</td>
                      </tr>
                    {/foreach}
                  {/if}
                </tbody>
              </table>
              <div class="row">
                <div class="table-footer">
                  <div class="col-md-6">
                  </div>
                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/user/usersScoresLogs?page=%page%&op='|cat:$op)}"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>

{include file='admin/after_body.phtml'}
<script type="text/javascript">

</script>
</html>