{include file='admin/before_body.phtml' title='添加用户'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='user_view'}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="{url('admin/user/')}">用户管理</a></li>
          <li class="current">添加用户</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-header">
              <h4>
                <i class="icon-reorder"></i> 添加用户
              </h4>
            </div>
            <div class="widget-content">
              <form class="form-horizontal row-border" id="validate" action="{url('admin/user/add/')}" method="POST">
                <!--logo-->
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <img src="{urlAvatar(null, 160)}" alt="用户头像">
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-md-3 control-label">
                    用户名：<span class="required"></span>
                  </label>
                  <div class="col-md-9">
                    <input type="text" name="username" class="form-control input-width-xxlarge required">
                  </div>
                </div>
                
                <div class="form-group">
                  <label class="col-md-3 control-label">
                    昵称：<span class="required"></span>
                  </label>
                  <div class="col-md-9">
                    <input type="text" name="nickname" class="form-control input-width-xxlarge required ">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-3 control-label">
                    电子邮箱：<span class="required"></span>
                  </label>
                  <div class="col-md-9">
                    <input type="text" name="email" class="form-control input-width-xxlarge required">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-3 control-label">
                    登录密码：<span class="required"></span>
                  </label>
                  <div class="col-md-9">
                    <input type="password" id="password" name="password" class="form-control input-width-xxlarge required">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-3 control-label">
                   确认密码：<span class="required"></span>
                  </label>
                  <div class="col-md-9">
                    <input type="password" name="conf_password" class="form-control input-width-xxlarge required equalTo:'#password'">
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-3 control-label">
                    状态：
                  </label>
                  <div class="col-md-9">
                    <label class="radio pull-left" style="width:80px;">
                      <input type="radio" name="status" class="uniform" checked="checked" value="1" />
                     有效
                    </label>
                    <label class="radio">
                      <input type="radio" name="status" class="uniform" value="0" />
                       禁用
                    </label>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-md-3 control-label">
                    角色列表：
                  </label>
                  <div class="col-md-9" style="width:530px;">
                    {foreach $roles as $role}
                    <div class="col-md-4">
                    <label class="checkbox-inline">
                      <input type="checkbox" name="roles[]" class="uniform" value="{$role->rid}">
                      {$role->name|escape}
                    </label>
                    </div>
                    {/foreach}
                  </div>
                </div>
                <div class="form-group form-actions">
                  <label class="col-md-3 control-label hidden-xs"></label>
                  <div class="col-md-9">
                    <input type="submit" value="保存提交" class="btn btn-primary">
                    <a href="{url('admin/user/')}" class="btn">返回用户列表</a>
                  </div>
                </div>
              </form>
            </div>  
          </div>
        </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>

{include file='admin/after_body.phtml'}

<script type="text/javascript">
$(document).ready(function() {
    $("#validate").validate({
        rules: {
            username: "required",
            nickname: "required",
            email: {
                required: true,
                email: true
            },
            password: {
                required: true
            },
            conf_password: {
                required: true,
                equalTo: "#password"
            }
        },
        messages: {
            username: "请输入用户名",
            nickname: "请输入昵称",
            email: {
                required: "请输入Email地址",
                email: "请输入正确的email地址"
            },
            password: {
                required: "请输入密码",
            },
            conf_password: {
                required: "请输入确认密码",
                equalTo: "两次输入密码不一致"
            }
        }
    });
    FormComponents.init();
});
</script>
</html>