{include file='admin/before_body.phtml' title='商家订单列表'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='merchant'}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li><i class="icon-home"></i><a href="{url('admin/merchant/')}">商家中心</a></li>
          <li class="current">发票列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-content no-padding">
              <form action="{url('admin/merchant/invoices')}" method="GET" id="form1" style="margin:0">
              <div class="row">
                <div class="dataTables_header clearfix">
                  <div class="col-md-3">
                     <div class="input-group">
                      <input type="text" name="merchantName" value="{$smarty.get.merchantName|default:''|escape}" placeholder="商家名称过滤.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                     </div>
                  </div>
                  <div class="col-md-2">
                     <div class="input-group">
                     <select name="invoiceStatus" id="invoiceStatus" class="select2" data-minimum-results-for-search="-1" style="width: 140px">
                        {$invoiceStatus = $smarty.get.invoiceStatus|default:-1}
                        <option value="-1"  {if $invoiceStatus != '0' || $invoiceStatus != '1' } selected {/if}>所有发票</option>
                        <option value="0" {if $invoiceStatus == '0'} selected {/if}>未开发票</option>
                        <option value="1" {if $invoiceStatus == '1'} selected {/if}>已开发票</option>
                      </select>
                     </div>
                  </div>
                  <div class="col-md-7">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/merchant/invoices?page=%page%&orderId='|cat:$orderId|cat:'&invoicestatus='|cat:$invoicestatus|cat:'&merchantName='|cat:$merchantName)}"}
                    </div>
                  </div>
                </div>
                <input type="submit"  style="display:none">
              </div>
              </form>
              <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
                <thead>
                  <tr>
                    <th width="150">商家名称</th>
                    <th>发票内容</th>
                    <th width="100">发票金额</th>
                    <th width="70">开票状态</th>
                    <th width="160">创建时间</th>
                  </tr>
                </thead>
                <tbody>
                  {if isset($invoicesList) && $invoicesList}
                    {foreach $invoicesList as $sa}
                      <tr>
                        <td>{$sa->seller|escape}</td>
                        <td>{$sa->content|escape}</td>
                        <td>{$sa->money}</td>
                        <td>
                          {if $sa->status == 1}
                            <span class="label label-success">已开发票</span>
                          {elseif $sa->status == 0}
                            <span class="label label-danger">未开</span>
                          {/if}
                        </td>
                        <td>{$sa->created|date_format:'Y-m-d G:i:s'}</td>
                      </tr>
                    {/foreach}
                  {/if}
                </tbody>
              </table>
              <div class="row">
                <div class="table-footer">
                  <div class="col-md-6">
                  </div>
                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/merchant/invoices?page=%page%&orderId='|cat:$orderId|cat:'&invoicestatus='|cat:$invoicestatus|cat:'&merchantName='|cat:$merchantName)}"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>

{include file='admin/after_body.phtml'}
<script type="text/javascript">
$('#invoiceStatus').change(function() {
    document.getElementById('form1').submit();
  });
</script>
</html>
