{include file='admin/before_body.phtml' title='许愿列表'}

<body>
{include file='admin/header.phtml'}

<div id="container" class="fixed-header {if isset($smarty.cookies.sidebar) && $smarty.cookies.sidebar}sidebar-closed{/if}">

  {include file='admin/sidebar.phtml' navigation='product_view'}
  {$rewardStatus = $smarty.get.rewardStatus|default:'-1'}
  {$productId = $smarty.get.productId|default:''}
  {$userName = $smarty.get.userName|default:''}

  <div id="content">
    <div class="container">
      <div class="crumbs">
        <ul id="breadcrumbs" class="breadcrumb">
          <li class="current">许愿用户列表</li>
        </ul>
      </div>
      <div class="page-header"></div>
      <div class="page-header"></div>
      {html_messages}
      <!-- start -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-content no-padding">
              <form action="{url('admin/channel/wishing')}" method="GET" id="form1" style="margin:0">
              <div class="row">
                <div class="dataTables_header clearfix">
                  <div class="col-md-2">
                     <div class="input-group">
                      <input type="text" name="productId" value="{$productId}" placeholder="产品ID过滤.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                     </div>
                  </div>
                  <div class="col-md-2">
                     <div class="input-group">
                      <input type="text" name="userName" value="{$userName}" placeholder="中奖联系人过滤.." class="form-control">
                      <span class="input-group-addon" onclick="document.getElementById('form1').submit();"><i  style="cursor:pointer;" class="icon-search"></i></span>
                     </div>
                  </div>
                  <div class="col-md-2">
                     <div class="input-group">
                     <select name="rewardStatus" id="rewardStatus" class="select2" data-minimum-results-for-search="-1" style="width: 140px">
                        <option value="-1"  {if $rewardStatus != '1' && $rewardStatus != '0'} selected {/if}>所有状态</option>
                        <option value="0" {if $rewardStatus == '0'} selected {/if}>未中状态</option>
                        <option value="1" {if $rewardStatus == '1'} selected {/if}>中奖状态</option>
                      </select>
                     </div>
                  </div>
                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/channel/wishing?page=%page%&pid='|cat:$productId|cat:'&Status='|cat:$rewardStatus|cat:'&nickname='|cat:$userName)}"}
                    </div>
                  </div>
                </div>
              </div>
                <input type="submit"  style="display:none">
              </form>
              <table class="table table-striped table-bordered table-hover table-checkable table-responsive datatable">
                <thead>
                  <tr>
                    <th width="80">许愿ID</th>
                    <th width="80">用户ID</th>
                    <th>留言内容</th>
                    <th width="70">许愿商品</th>
                    <th width="110">手机号码</th>
                    <th width="120">中奖联系人</th>
                    <th width="80">中奖状态</th>
                    <th>联系地址</th>
                    <th width="160">创建时间</th>
                  </tr>
                </thead>
                <tbody>
                  {if isset($wishingList) && $wishingList}
                    {foreach $wishingList as $sa}
                      <tr>
                        <td>{$sa->did}</td>
                        <td>{$sa->uid}</td>
                        <td>{$sa->content|escape}</td>
                        <td>{$sa->pid}</a></td>
                        <td>{$sa->telphone|escape}</td>
                        <td>{$sa->nickname|escape}</td>
                        <td>
                          {if $sa->status == 0 }
                            <span class="label label-danger">未中奖</span>
                          {elseif $sa->status == 1 }
                            <span class="label label-success">中奖</span>
                            
                          {/if}
                        </td>
                        <td>{$sa->address|escape}</td> 
                        <td>{$sa->created|date_format:'Y-m-d G:i:s'}</td>
                      </tr>
                    {/foreach}
                  {/if}
                </tbody>
              </table>
              <div class="row">
                <div class="table-footer">
                  <div class="col-md-6">
                  </div>
                  <div class="col-md-6">
                    <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('admin/channel/wishing?page=%page%&pid='|cat:$productId|cat:'&status='|cat:$rewardStatus|cat:'&nickame='|cat:$userName)}"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /end -->
    </div>
  </div>
</div>
</body>

{include file='admin/after_body.phtml'}
<script type="text/javascript">
  $('#rewardStatus').change(function() {
    document.getElementById('form1').submit();
  });
</script>
</html>
