{if isset($logsList) && $logsList}
      <div class="row">
        <div class="col-md-12">
          <div class="widget box">
            <div class="widget-header">
              <h4><i class="icon-reorder"></i> 操作日志</h4>
            </div>
            <div class="widget-content">
              <form class="form-horizontal row-border">
{foreach $logsList as $sa}
                <div class="form-group">
                  <label class="col-md-3 control-label" style="text-align:right;">
                    {$sa->created|date_format:'Y-m-d G:i:s'}
                  </label>
                  <div class="col-md-9">
                    <label class="checkbox-inline">
                      {$sa->body}
                    </label>
                  </div>
                </div>
{/foreach}
              </form>
            </div>
          </div>
        </div>
      </div>
{/if}